---
- name: Stop Tomcat
  hosts: 54.215.34.146
  become: true
  remote_user: root  # Specify your SSH user here
  tasks:
    - name: Ensure Tomcat is stopped
      systemd:
        name: tomcat
        state: stopped

